---
name: Samba Backup
version: 5.2.0
slug: samba_backup
description: Create backups and store them on a Samba share
url: https://github.com/thomasmauerer/hassio-addons/tree/master/samba-backup
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
homeassistant_api: true
hassio_api: true
hassio_role: manager
stdin: true
map:
  - backup:rw
image: thomasmauerer/samba-backup-{arch}
init: false
options:
  host: null
  share: null
  target_dir: ""
  username: ""
  password: ""
  keep_local: all
  keep_remote: all
  trigger_time: 00:00
  trigger_days:
    - Mon
    - Tue
    - Wed
    - Thu
    - Fri
    - Sat
    - Sun
  exclude_addons: []
  exclude_folders: []
schema:
  host: str
  share: str
  target_dir: str
  username: str
  password: password
  keep_local: match(^(all|[0-9]+)$)
  keep_remote: match(^(all|[0-9]+)$)
  trigger_time: match(^(manual|([0-1][0-9]|2[0-3]):[0-5][0-9])$)
  trigger_days:
    - match(Mon|Tue|Wed|Thu|Fri|Sat|Sun)
  exclude_addons:
    - str
  exclude_folders:
    - str
  backup_name: str?
  backup_password: str?
  workgroup: str?
  compatibility_mode: bool?
  skip_precheck: bool?
  log_level: list(debug|info|warning|error)?
